export const SIGNIN_USER = 'USER/SIGNIN_USER'
export const SIGNOUT_USER = 'USER/SIGNOUT_USER'
export const AUTH_REQUEST_FAILED = 'USER/AUTH_REQUEST_FAILED'
export const SIGNIN_USER_ASYNC = 'USER/SIGNIN_USER_ASYNC'
export const SIGNOUT_USER_ASYNC = 'USER/SIGNOUT_USER_ASYNC'

export const SET_APP_LOADING = 'APP/SET_APP_LOADING'
